export const APP_ROUTES = {
  DASHBOARD: "/admin/dashboard",
  PROFILE: "/admin/profile",
  APPOINTMENTS: "/admin/appointments",
  USERS: "/admin/users",
  PATIENTS: "/admin/patients",
  PATIENT_DETAILS: "/admin/patients/details",
  APPOINTMENT_CONFIRM: "/admin/appointment/confirm",
  LOGIN: "/",
  REGISTER: "/register",
  APPOINTMENT_LIST: "/admin/appointment-list",
  APPOINTMENT_DETAILS: "/admin/appointments/details",
  MEDICATION: "/admin/medications",
  AILMENTS: "/admin/ailments",
  APPOINTMENT_FEEDBACKS: "/admin/feedbacks",
};
